// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM9ksnNLrmDT1wwUn6jt47EevjftAVR_4',
    appId: '1:1043452257427:web:a6b2af61291ffc614e5966',
    messagingSenderId: '1043452257427',
    projectId: 'gemchat-a0a2b',
    authDomain: 'gemchat-a0a2b.firebaseapp.com',
    storageBucket: 'gemchat-a0a2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN7sgihuDYJNaXWMPFZvFjm7Q2Gboo27A',
    appId: '1:1043452257427:android:236560e3120f0df64e5966',
    messagingSenderId: '1043452257427',
    projectId: 'gemchat-a0a2b',
    storageBucket: 'gemchat-a0a2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBa0dHq3HLQw1tydYK87TtKRzRRrZ_uIQ',
    appId: '1:1043452257427:ios:14c4c83216c0ee694e5966',
    messagingSenderId: '1043452257427',
    projectId: 'gemchat-a0a2b',
    storageBucket: 'gemchat-a0a2b.firebasestorage.app',
    iosBundleId: 'com.example.geminiChatBot',
  );
}
